const RESET = 'form/RESET';
const MOUNT = 'form/MOUNT';
const DESTROY = 'form/DESTROY';
const SET_INITIAL_VALUES = 'form/SET_INITIAL_VALUES';
const SET_FIELD_VALUE = 'form/SET_FIELD_VALUE';
const CHANGE_FIELD = 'form/CHANGE_FIELD';
const REGISTER_FIELD = 'form/REGISTER_FIELD';
const UNREGISTER_FIELD = 'form/UNREGISTER_FIELD';
const SET_VALID = 'form/SET_VALID';
const SET_DATA = 'form/SET_DATA';

export default {
  RESET,
  MOUNT,
  DESTROY,
  REGISTER_FIELD,
  UNREGISTER_FIELD,
  SET_INITIAL_VALUES,
  SET_FIELD_VALUE,
  CHANGE_FIELD,
  SET_VALID,
  SET_DATA
};
